name: idiary
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_quill: ^7.4.7
  flutter_riverpod: ^2.4.1
  riverpod_annotation: ^2.1.6
  go_router: ^11.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
